import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-oxygen",
});

export const metadata: Metadata = {
  title: "Prasoon - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        <div className="p-4 flex flex-col items-center justify-center gap-3">
          <div className="main-container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
